// This is a generated class, generated by the DataClassGenerator.
// To read more about the tool:https://xapt.sharepoint.com/:w:/s/MobileTeam/EVd0056mkIxApxs4_wo3f2IB6wWS4ydQ7TvbjOB-oez1NQ?e=EEWfDO

import NMDEF_Sync

public class DamageCodesDAO: NSObject, SyncDataAccessObject {
    public typealias Model = DamageCodes
}