// This is a generated class, generated by the DataClassGenerator.
// To read more about the tool:https://xapt.sharepoint.com/:w:/s/MobileTeam/EVd0056mkIxApxs4_wo3f2IB6wWS4ydQ7TvbjOB-oez1NQ?e=EEWfDO

import NMDEF_Sync

public class RenWorkerWarehouseDAO: NSObject, DataAccessObjectProtocol {
    public typealias Model = RenWorkerWarehouse
    public var priority: Int {
        get {
            return 10
        }
    }

    public override init() {
        super.init()
    }
}
		