// This is a generated class, generated by the DataClassGenerator.
// To read more about the tool:https://xapt.sharepoint.com/:w:/s/MobileTeam/EVd0056mkIxApxs4_wo3f2IB6wWS4ydQ7TvbjOB-oez1NQ?e=EEWfDO

import NMDEF_Sync

public class MOB_DamageHistory: BaseEntity {
    @objc dynamic var dataAreaId: String = ""
    @objc dynamic var eqDamageHistoryId: String = ""
    @objc dynamic var damageCreatedDateTime: Date = Date(timeIntervalSince1970: 1)
    @objc dynamic var xap_emrTable_EMRId: String = ""
    @objc dynamic var damageDescription: String = ""
    @objc dynamic var updatedAt: Date = Date(timeIntervalSince1970: 1)
    @objc dynamic var xap_EquipmentTable_EquipmentId: String = ""
    @objc dynamic var xap_DamageCodes_DamageCode: String = ""
    @objc dynamic var user: String = ""

    @objc dynamic var damageStatus: String = "Active"
}
		