// This is a generated class, generated by the DataClassGenerator.
// To read more about the tool:https://xapt.sharepoint.com/:w:/s/MobileTeam/EVd0056mkIxApxs4_wo3f2IB6wWS4ydQ7TvbjOB-oez1NQ?e=EEWfDO

import NMDEF_Sync

public class MOB_ModDateTimes: BaseEntity {
    @objc dynamic var dataAreaId: String = ""
    @objc dynamic var updatedAt: Date = Date(timeIntervalSince1970: 1)
    @objc dynamic var refTableId: Int = 0


    public override class func ignoredProperties() -> [String] {
        return ["version", "createdAt"]
    }
}